name: Mod publication

on: [ workflow_dispatch ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x gradlew
      - name: Build
        run: ./gradlew build

  curseforge:
    name: Curseforge Publication
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x gradlew
      - name: Publish
        run: ./gradlew curseforge
        env:
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}

  modrinth:
    name: Modrinth Publication
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x gradlew
      - name: Publish
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

  maven:
    name: Maven Publication
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x gradlew
      - name: Publish
        run: ./gradlew publish
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
